version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "svelte"
    labels:
        - 'dependencies'
        - 'NPM Stuff'
        
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
        interval: 'monthly'
    commit-message:
        prefix: 'ci'
    labels:
      - 'dependencies'
      - 'Github Actions'
